globalThis.process ??= {};
globalThis.process.env ??= {};
import { c as createComponent } from "./astro-component_DBIynOy6.mjs";
import { m as maybeRenderHead, r as renderTemplate, a as addAttribute } from "./sequence_CNN-ZGRA.mjs";
import { r as renderScript } from "./global_CZrsF2AQ.mjs";
const $$DonateWidget = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$props, $$slots);
  Astro2.self = $$DonateWidget;
  const { settings, variant = "compact" } = Astro2.props;
  if (!settings || settings.enabled === 0) {
    return;
  }
  return renderTemplate`${variant === "inline" ? renderTemplate`<!-- ===== Inline variant — always visible, hero-style ===== -->
  ${maybeRenderHead()}<div class="donate-inline relative overflow-hidden rounded-3xl border border-outline-variant/30 bg-surface-container" data-astro-cid-fuyrfybf><!-- Decorative glows --><div class="absolute -top-24 -right-24 w-72 h-72 bg-primary/8 rounded-full blur-3xl pointer-events-none" data-astro-cid-fuyrfybf></div><div class="absolute -bottom-20 -left-20 w-56 h-56 bg-tertiary/6 rounded-full blur-3xl pointer-events-none" data-astro-cid-fuyrfybf></div><div class="relative z-10 flex flex-col md:flex-row items-center gap-8 p-8 md:p-12" data-astro-cid-fuyrfybf><!-- Left: text content --><div class="flex-1 text-center md:text-left space-y-4" data-astro-cid-fuyrfybf><div class="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-primary/10 text-primary md:mx-0 mx-auto" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-3xl" data-astro-cid-fuyrfybf>volunteer_activism</span></div><h3 class="text-headline-md text-white" data-astro-cid-fuyrfybf>${settings.title}</h3><p class="text-sm text-on-surface-variant leading-relaxed max-w-md" data-astro-cid-fuyrfybf>${settings.message}</p><div class="flex items-center gap-3 text-xs text-on-surface-variant pt-2 justify-center md:justify-start" data-astro-cid-fuyrfybf><span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/5 border border-outline-variant/30" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[14px] text-primary" data-astro-cid-fuyrfybf>qr_code_2</span>
Quét để ủng hộ
</span>${settings.payment_methods && renderTemplate`<span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/5 border border-outline-variant/30" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[14px] text-primary" data-astro-cid-fuyrfybf>account_balance</span>${settings.payment_methods}</span>`}</div></div><!-- Right: QR code --><div class="shrink-0" data-astro-cid-fuyrfybf><div class="donate-qr-wrap relative p-3 bg-white rounded-2xl shadow-[0_8px_32px_rgba(146,204,255,0.12)] border border-white/10" data-astro-cid-fuyrfybf><img${addAttribute(settings.qr_url, "src")} alt="QR Code ủng hộ" class="w-52 h-52 md:w-56 md:h-56" loading="lazy" decoding="async" data-astro-cid-fuyrfybf><!-- Subtle corner accents --><div class="absolute top-1.5 left-1.5 w-4 h-4 border-t-2 border-l-2 border-primary/40 rounded-tl-lg" data-astro-cid-fuyrfybf></div><div class="absolute top-1.5 right-1.5 w-4 h-4 border-t-2 border-r-2 border-primary/40 rounded-tr-lg" data-astro-cid-fuyrfybf></div><div class="absolute bottom-1.5 left-1.5 w-4 h-4 border-b-2 border-l-2 border-primary/40 rounded-bl-lg" data-astro-cid-fuyrfybf></div><div class="absolute bottom-1.5 right-1.5 w-4 h-4 border-b-2 border-r-2 border-primary/40 rounded-br-lg" data-astro-cid-fuyrfybf></div></div><p class="text-center text-[11px] text-on-surface-variant mt-3" data-astro-cid-fuyrfybf>
Quét mã QR với ứng dụng ngân hàng
</p><button type="button"${addAttribute(settings.qr_url, "data-donate-qr-url")} class="donate-download-btn mt-3 w-full inline-flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-primary/10 border border-primary/30 text-primary text-sm font-semibold hover:bg-primary/20 hover:border-primary/50 active:scale-95 transition-all" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[18px]" data-astro-cid-fuyrfybf>download</span><span class="donate-download-label" data-astro-cid-fuyrfybf>Lưu hình QR</span></button></div></div></div>` : renderTemplate`<!-- ===== Compact variant — collapsible (book, resources) ===== -->
  <div id="support-widget" class="mt-12 transition-all duration-300" data-astro-cid-fuyrfybf><button id="support-trigger" class="group flex items-center gap-2 mx-auto px-5 py-2.5 rounded-full border border-outline-variant/40 text-on-surface-variant hover:text-primary hover:border-primary/40 transition-all duration-200 cursor-pointer select-none" aria-expanded="false" aria-controls="support-panel" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[18px] text-primary group-hover:scale-110 transition-transform duration-200" data-astro-cid-fuyrfybf>favorite</span><span class="text-sm font-medium" data-astro-cid-fuyrfybf>${settings.title}</span><span id="support-chevron" class="material-symbols-outlined text-[16px] transition-transform duration-300" data-astro-cid-fuyrfybf>expand_more</span></button><div id="support-panel" class="hidden mt-3 p-6 bg-surface-container rounded-2xl border border-outline-variant/30 text-center" role="region" aria-labelledby="support-trigger" data-astro-cid-fuyrfybf><div class="inline-flex items-center justify-center w-12 h-12 rounded-full bg-primary/10 text-primary mb-3" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-2xl" data-astro-cid-fuyrfybf>volunteer_activism</span></div><h3 class="text-title-md text-white mb-2" data-astro-cid-fuyrfybf>${settings.title}</h3><p class="text-sm text-on-surface-variant mb-5 max-w-md mx-auto" data-astro-cid-fuyrfybf>${settings.message}</p><div class="inline-block p-4 bg-white rounded-2xl mb-4" data-astro-cid-fuyrfybf><img${addAttribute(settings.qr_url, "src")} alt="QR Code ủng hộ" class="w-44 h-44" loading="lazy" decoding="async" data-astro-cid-fuyrfybf></div><p class="text-xs text-on-surface-variant mt-3" data-astro-cid-fuyrfybf>
Quét mã QR với ứng dụng ngân hàng để ủng hộ qua chuyển khoản
</p><button type="button"${addAttribute(settings.qr_url, "data-donate-qr-url")} class="donate-download-btn mt-3 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 border border-primary/30 text-primary text-xs font-semibold hover:bg-primary/20 hover:border-primary/50 active:scale-95 transition-all" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[14px]" data-astro-cid-fuyrfybf>download</span><span class="donate-download-label" data-astro-cid-fuyrfybf>Lưu hình QR</span></button>${settings.payment_methods && renderTemplate`<div class="flex items-center justify-center gap-2 mt-2 text-xs text-on-surface-variant" data-astro-cid-fuyrfybf><span class="material-symbols-outlined text-[14px]" data-astro-cid-fuyrfybf>qr_code_2</span><span data-astro-cid-fuyrfybf>Supports: ${settings.payment_methods}</span></div>`}</div></div>`}${renderScript($$result, "C:/dentalempireos/src/components/book/DonateWidget.astro?astro&type=script&index=0&lang.ts")}`;
}, "C:/dentalempireos/src/components/book/DonateWidget.astro", void 0);
export {
  $$DonateWidget as $
};
