globalThis.process ??= {};
globalThis.process.env ??= {};
import { c as createComponent } from "./astro-component_DBIynOy6.mjs";
import { r as renderTemplate, m as maybeRenderHead, a as addAttribute } from "./sequence_CNN-ZGRA.mjs";
import { r as renderComponent } from "./worker-entry_VoTlS2tl.mjs";
import { r as renderScript } from "./global_Ia4nBvKf.mjs";
import { $ as $$AdminLayout } from "./AdminLayout_Do1AQBaG.mjs";
import { env } from "cloudflare:workers";
import { getCategories as listCategories, getTags as listTags, buildCategoryTree, flattenCategoryTree } from "./blog-db_CoZeeOQQ.mjs";
const prerender = false;
const $$New = createComponent(async ($$result, $$props, $$slots) => {
  const db = env.DB;
  const [flatCategories, tags, chapters, scanners] = await Promise.all([
    listCategories(db),
    listTags(db),
    db.prepare('SELECT id, title, chapter_number FROM "chapter" ORDER BY "order"').all(),
    db.prepare('SELECT id, name FROM "survey_definition" ORDER BY "created_at" DESC').all()
  ]);
  const categoryTree = buildCategoryTree(flatCategories);
  const categoryOptions = flattenCategoryTree(categoryTree);
  return renderTemplate`${renderComponent($$result, "AdminLayout", $$AdminLayout, { "title": "Viết bài mới | Blog Admin" }, { "default": async ($$result2) => renderTemplate` ${maybeRenderHead()}<div class="max-w-[900px] w-full mx-auto flex flex-col gap-6"> <!-- Header --> <div class="flex items-center justify-between"> <div> <h2 class="text-3xl font-bold text-white">Viết bài mới</h2> <p class="text-on-surface-variant text-sm mt-1">Tạo bài viết blog mới</p> </div> <a href="/admin/blog" class="px-4 py-2 border border-outline-variant text-on-surface-variant rounded-xl text-sm font-bold hover:border-primary hover:text-primary transition-all flex items-center gap-2"> <span class="material-symbols-outlined text-[18px]">arrow_back</span>
Quay lại
</a> </div> <form id="blog-post-form" class="flex flex-col gap-6"> <!-- Cover Image --> <section class="glass-card rounded-xl p-5"> <h3 class="text-sm font-bold text-white mb-4 flex items-center gap-2"> <span class="material-symbols-outlined text-primary text-[18px]">image</span>
Ảnh đại diện
</h3> <div class="flex flex-col sm:flex-row gap-4 items-start"> <div class="relative"> <img id="cover-preview" src="" alt="" class="hidden w-48 h-32 rounded-xl object-cover border border-outline-variant"> <div id="cover-placeholder" class="w-48 h-32 rounded-xl bg-surface-container-high border border-dashed border-outline-variant flex items-center justify-center"> <span class="material-symbols-outlined text-4xl text-on-surface-variant/30">add_photo_alternate</span> </div> <button type="button" id="cover-remove" class="hidden absolute -top-2 -right-2 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center hover:bg-red-600 transition-colors"> <span class="material-symbols-outlined text-[14px]">close</span> </button> </div> <div class="flex flex-col gap-2"> <input type="hidden" name="cover_url" id="cover-url" value=""> <input type="hidden" name="cover_alt" id="cover-alt" value=""> <button type="button" id="upload-cover-btn" class="px-4 py-2 bg-surface-container-high border border-outline-variant text-white rounded-xl text-sm font-semibold hover:border-primary transition-all"> <span class="material-symbols-outlined text-[16px] align-middle mr-1">upload</span>
Tải ảnh lên
</button> <p class="text-xs text-on-surface-variant">PNG, JPG, WEBP · Tối đa 5MB · Khuyến nghị 1200×630</p> <p id="cover-warning" class="hidden text-xs font-semibold text-yellow-400 mt-1 flex items-start gap-1.5"> <span class="material-symbols-outlined text-[14px] mt-0.5">warning</span> <span>Bài này chưa có ảnh bìa — khi share Facebook/Zalo sẽ dùng ảnh mặc định của site.</span> </p> </div> </div> </section> <!-- Basic Info --> <section class="glass-card rounded-xl p-5"> <h3 class="text-sm font-bold text-white mb-4 flex items-center gap-2"> <span class="material-symbols-outlined text-primary text-[18px]">article</span>
Thông tin cơ bản
</h3> <div class="grid grid-cols-1 gap-4"> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Tiêu đề <span class="text-red-400">*</span></label> <input type="text" name="title" id="post-title" required placeholder="Nhập tiêu đề bài viết..." class="w-full px-4 py-3 bg-surface-container border border-outline-variant rounded-xl text-white text-base font-semibold focus:ring-2 focus:ring-primary focus:outline-none placeholder:text-white/20"> </div> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Mô tả ngắn <span class="text-red-400">*</span></label> <textarea name="description" id="post-description" required rows="2" placeholder="Mô tả ngắn 1-2 câu hiển thị trong danh sách..." class="w-full px-4 py-3 bg-surface-container border border-outline-variant rounded-xl text-white text-sm focus:ring-2 focus:ring-primary focus:outline-none placeholder:text-white/20 resize-none"></textarea> </div> <div class="grid grid-cols-1 sm:grid-cols-2 gap-4"> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Slug <span class="text-red-400">*</span></label> <input type="text" name="slug" id="post-slug" required placeholder="slug-bai-viet" class="w-full px-4 py-2 bg-surface-container border border-outline-variant rounded-xl text-white text-sm focus:ring-2 focus:ring-primary focus:outline-none placeholder:text-white/20"> <p class="text-[10px] text-on-surface-variant/50 mt-1">URL: /blog/[slug]</p> </div> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Chuyên mục</label> <select name="category_id" id="post-category" class="w-full px-4 py-2 bg-surface-container border border-outline-variant rounded-xl text-white text-sm focus:ring-2 focus:ring-primary focus:outline-none"> <option value="">— Không chọn —</option> ${categoryOptions.map((opt) => renderTemplate`<option${addAttribute(opt.id, "value")}> ${opt.indent > 0 ? "└── " : ""}${opt.name} </option>`)} </select> </div> </div> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Tags</label> <div class="flex flex-wrap gap-2 p-3 bg-surface-container border border-outline-variant rounded-xl min-h-[48px]"> ${tags.map((tag) => renderTemplate`<label class="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container-high border border-outline-variant cursor-pointer hover:border-primary transition-all text-xs text-on-surface-variant has-[:checked]:bg-primary/10 has-[:checked]:border-primary has-[:checked]:text-primary"> <input type="checkbox" name="tags"${addAttribute(tag.id, "value")} class="hidden">
#${tag.name} </label>`)} </div> </div> </div> </section> <!-- Content --> <section class="glass-card rounded-xl p-5"> <h3 class="text-sm font-bold text-white mb-4">Nội dung</h3> <div id="rich-editor-container" class="min-h-[400px]"></div> <input type="hidden" name="blocks_json" id="blocks-json" value="[]"> </section> <!-- Options --> <section class="glass-card rounded-xl p-5"> <h3 class="text-sm font-bold text-white mb-4 flex items-center gap-2"> <span class="material-symbols-outlined text-primary text-[18px]">settings</span>
Tùy chọn
</h3> <div class="grid grid-cols-1 sm:grid-cols-2 gap-4"> <div class="flex flex-col gap-3"> <label class="flex items-center gap-3 cursor-pointer"> <input type="checkbox" name="is_featured" id="is-featured" class="w-4 h-4 accent-primary"> <div> <span class="text-sm font-semibold text-white">Tin nổi bật</span> <p class="text-xs text-on-surface-variant">Hiển thị trong mục "Tin nổi bật" trang chủ</p> </div> </label> <label class="flex items-center gap-3 cursor-pointer"> <input type="checkbox" name="is_pinned" id="is-pinned" class="w-4 h-4 accent-primary"> <div> <span class="text-sm font-semibold text-white">Ghim bài</span> <p class="text-xs text-on-surface-variant">Luôn hiển thị đầu danh sách</p> </div> </label> <label class="flex items-center gap-3 cursor-pointer"> <input type="checkbox" name="is_recommended" id="is-recommended" class="w-4 h-4 accent-primary"> <div> <span class="text-sm font-semibold text-white">Khuyến nghị</span> <p class="text-xs text-on-surface-variant">Badge "Recommend" trên card</p> </div> </label> </div> <div class="flex flex-col gap-3"> <label class="flex items-center gap-3 cursor-pointer"> <input type="checkbox" name="status_published" id="status-published" class="w-4 h-4 accent-primary"> <div> <span class="text-sm font-semibold text-white">Xuất bản ngay</span> <p class="text-xs text-on-surface-variant">Bài sẽ hiển thị công khai</p> </div> </label> </div> </div> <!-- Liên kết Sách & Scanner --> <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 border-t border-outline-variant/50 mt-2"> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Chương sách liên quan</label> <select name="chapter_id" id="chapter-id" class="w-full px-4 py-2 bg-surface-container border border-outline-variant rounded-xl text-white text-sm focus:ring-2 focus:ring-primary focus:outline-none"> <option value="">— Không chọn —</option> ${chapters.results.map((ch) => renderTemplate`<option${addAttribute(ch.id, "value")}>Chương ${ch.chapter_number}: ${ch.title}</option>`)} </select> </div> <div> <label class="block text-xs font-semibold text-on-surface-variant mb-1">Scanner/Bài test liên quan</label> <select name="scanner_id" id="scanner-id" class="w-full px-4 py-2 bg-surface-container border border-outline-variant rounded-xl text-white text-sm focus:ring-2 focus:ring-primary focus:outline-none"> <option value="">— Không chọn —</option> ${scanners.results.map((s) => renderTemplate`<option${addAttribute(s.id, "value")}>${s.name}</option>`)} </select> </div> </div> </section> <!-- Submit --> <div class="flex items-center justify-end gap-3 pb-4"> <a href="/admin/blog" class="px-6 py-3 border border-outline-variant text-on-surface-variant rounded-xl font-bold hover:border-primary hover:text-primary transition-all">
Hủy
</a> <button type="submit" id="submit-btn" class="px-8 py-3 bg-primary-container text-white rounded-xl font-bold cyan-glow hover:opacity-90 active:scale-95 transition-all flex items-center gap-2"> <span class="material-symbols-outlined text-[20px]">save</span>
Lưu bài viết
</button> </div> </form> </div> ` })} ${renderScript($$result, "C:/dentalempireos/src/pages/admin/blog/new.astro?astro&type=script&index=0&lang.ts")}`;
}, "C:/dentalempireos/src/pages/admin/blog/new.astro", void 0);
const $$file = "C:/dentalempireos/src/pages/admin/blog/new.astro";
const $$url = "/admin/blog/new";
const _page = /* @__PURE__ */ Object.freeze(/* @__PURE__ */ Object.defineProperty({
  __proto__: null,
  default: $$New,
  file: $$file,
  prerender,
  url: $$url
}, Symbol.toStringTag, { value: "Module" }));
const page = () => _page;
export {
  page
};
