-- Fix Vietnamese diacritics for scale_labels_vi in batch 3-4 scanners
-- Root cause: update-batch3-4-vietnamese.sql only updated label_vi, not scale_labels_vi

-- === 23: marketing-content-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có content plan, đăng bài tùy ý","2":"Có đăng bài nhưng không có lịch cụ thể","3":"Có lịch đăng bài nhưng chưa có target audience rõ ràng","4":"Có content calendar và target audience được định nghĩa","5":"Content strategy đầy đủ: calendar + audience + topics + SEO strategy"}' WHERE question_id = 'mc_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Chỉ có hình ảnh đơn giản, không có video, nội dung yếu","2":"Có hình ảnh tốt nhưng ít video và nội dung chưa chỉnh chu","3":"Có hình ảnh và video chất lượng trung bình","4":"Content chất lượng tốt: hình ảnh đẹp, video hữu ích, văn bản rõ ràng","5":"Content xuất sắc: production quality cao, video storytelling, patient education content"}' WHERE question_id = 'mc_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có kênh nào được chăm sóc tốt","2":"Chỉ có Facebook, các kênh khác bỏ hoặc thật người theo dõi","3":"Có 1-2 kênh hoạt động nhưng không có strategy","4":"Multi-channel presence với content adapted cho từng kênh","5":"Omni-channel content strategy: adapted content + optimal posting time + cross-promotion"}' WHERE question_id = 'mc_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có content trên website hoặc blog","2":"Có blog nhưng không tối ưu SEO","3":"Có một số bài SEO nhưng chưa có system","4":"SEO content strategy: keyword research + on-page SEO + regular posting","5":"Comprehensive SEO: keyword strategy + technical SEO + local SEO + content hub + backlinks"}' WHERE question_id = 'mc_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có engagement, bài đăng không ai quan tâm","2":"Ít engagement, một vài lượt thích","3":"Engagement trung bình, có tương tác","4":"Engagement tốt: thích, bình luận, chia sẻ","5":"Engagement mạnh: community xây dựng + organic growth + brand advocacy"}' WHERE question_id = 'mc_q5';

-- === 24: loi-nhu-quan-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không biết, chỉ nhìn số dư cuối ngày","2":"Có nhưng rời rạc, không hệ thống","3":"Có báo cáo hàng tháng cơ bản","4":"Báo cáo P&L đầy đủ, hàng tuần cập nhật","5":"P&L hàng tuần + dashboard realtime + phân tích biên lợi nhuận"}' WHERE question_id = 'ln_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có kế hoạch, sống ngày nào hay ngày đó","2":"Có mục tiêu chung nhưng không có kế hoạch cụ thể","3":"Có kế hoạch sơ lược nhưng không theo dõi tiến độ","4":"Có kế hoạch chi tiết với KPI và milestone","5":"Kế hoạch chiến lược rõ ràng: vision, 1-3 năm, quarterly OKR"}' WHERE question_id = 'ln_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Ít hơn 20% thời gian","2":"20-40% thời gian","3":"40-60% thời gian","4":"60-80% thời gian","5":"Trên 80% thời gian"}' WHERE question_id = 'ln_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có hệ thống, phụ thuộc vào khách cũ giới thiệu","2":"Có một số nỗ lực marketing nhưng không có hệ thống","3":"Có chiến lược thu hút bệnh nhân nhưng chưa chặt chẽ","4":"Có hệ thống: marketing + referral + retention + follow-up","5":"Hệ thống toàn diện: acquisition + experience + loyalty + recovery"}' WHERE question_id = 'ln_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không đầu tư thời gian hoặc tiền bạc vào việc học kinh doanh","2":"Thỉnh thoảng đọc bài viết nhưng không có hệ thống","3":"Tham gia một vài khóa học hoặc cộng đồng","4":"Đầu tư đều đặn: sách, khóa học, cộng đồng doanh nhân","5":"Học tập liên tục với hệ thống: mentorship, coaching, mastermind group"}' WHERE question_id = 'ln_q5';

-- === 25: hieu-qua-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Trên 30 phút","2":"15-30 phút","3":"5-15 phút","4":"Dưới 5 phút","5":"Luôn đúng giờ hoặc trước giờ hẹn"}' WHERE question_id = 'hq_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Mỗi lần một kiểu","2":"Có SOP nhưng không nhất quán","3":"Có SOP, đa số nhất quán","4":"SOP rõ ràng + đo lường + cải tiến","5":"Seamless patient journey, mọi step optimized"}' WHERE question_id = 'hq_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không rõ ràng, mỗi người tự quyết định hoặc chờ chỉ đạo","2":"Biết công việc chính nhưng không rõ quyền hạn","3":"Có mô tả công việc nhưng chưa đầy đủ","4":"Rõ ràng về trách nhiệm và có quy trình báo cáo","5":"Có RACI matrix, KPIs cá nhân, và quyền hạn rõ ràng cho từng vai trò"}' WHERE question_id = 'hq_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không dùng công nghệ để tự động hóa","2":"Dùng một vài công cụ nhưng không có hệ thống","3":"Có một số công cụ số nhưng chưa kết nối","4":"Công nghệ được sử dụng đều đặn, tiết kiệm thời gian","5":"Tự động hóa toàn diện: booking, nhắc nhở, báo cáo, CRM"}' WHERE question_id = 'hq_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không theo dõi chi phí cụ thể, chi tiêu tùy hứng","2":"Theo dõi chi phí lớn nhưng không chi tiết","3":"Có theo dõi chi phí hàng tháng nhưng chưa phân tích sâu","4":"Theo dõi chi tiết, phân tích chi phí theo từng hạng mục","5":"Hệ thống quản lý chi phí: budget, variance analysis, cost optimization"}' WHERE question_id = 'hq_q5';

-- === 26: co-so-vat-chat-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không gian chật hẹp, không thông, bệnh nhân ngồi chờ trong điều kiện không thoải mái","2":"Có không gian nhưng chưa được tối ưu về bố trí và cảm giác","3":"Không gian cơ bản sạch sẽ nhưng chưa tạo ấn tượng đặc biệt","4":"Không gian được thiết kế tốt, sạch sẽ, và tạo cảm giác chuyên nghiệp","5":"Không gian xuất sắc: thiết kế chủ đạo, sạch sẽ, tiện nghi, và tạo trải nghiệm tích cực"}' WHERE question_id = 'cs_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Thiết bị cũ, hỏng, hoặc thiếu thường xuyên","2":"Có thiết bị cơ bản nhưng chưa được bảo trì tốt","3":"Thiết bị được bảo trì nhưng chưa cập nhật công nghệ mới","4":"Thiết bị tốt, được bảo trì định kỳ và cập nhật khi cần","5":"Thiết bị hiện đại, được bảo trì chu đáo, và luôn sẵn sàng cho mọi ca điều trị"}' WHERE question_id = 'cs_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Tiêu chuẩn vệ sinh cơ bản, có thể còn thiếu sót","2":"Có quy trình vệ sinh nhưng chưa hệ thống và không nhất quán","3":"Quy trình vệ sinh cơ bản được tuân thủ","4":"Quy trình vệ sinh nghiêm ngặt, được đào tạo và theo dõi","5":"Tiêu chuẩn vô trùng cao nhất: quy trình chuẩn quốc tế, audit định kỳ, minh bạch với bệnh nhân"}' WHERE question_id = 'cs_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có tiện nghi cho bệnh nhân chờ","2":"Có ghế ngồi cơ bản, không có tiện nghi khác","3":"Có một vài tiện nghi cơ bản nhưng không được duy trì tốt","4":"Đủ tiện nghi cơ bản: wifi, nước uống, và sạc điện thoại","5":"Trải nghiệm chờ đợi tốt: wifi, nước uống, sạc, tạp chí, và có thông tin giáo dục bệnh nhân"}' WHERE question_id = 'cs_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Vị trí khó tìm, không có chỗ đỗ xe","2":"Vị trí khó tìm nhưng có chỗ đỗ xe","3":"Vị trí khá thuận tiện hoặc có chỗ đỗ xe","4":"Vị trí thuận tiện, có chỗ đỗ xe, và có biển chỉ dẫn rõ ràng","5":"Vị trí lý tưởng: dễ tìm, đỗ xe thuận tiện, có biển chỉ dẫn rõ ràng, và bản đồ online"}' WHERE question_id = 'cs_q5';

-- === 27: phan-biet-thuong-hieu-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không rõ điều gì khác biệt, giá là yếu tố chính","2":"Có một vài điều khác biệt nhưng chưa rõ ràng và không nhất quán","3":"Có positioning rõ ràng nhưng chưa được truyền tải tốt","4":"Có positioning rõ ràng và nhất quán, đội ngũ có thể diễn đạt","5":"Brand positioning mạnh mẽ: tagline, USP rõ ràng, và được truyền tải trong mọi touchpoint"}' WHERE question_id = 'pb_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có brand identity rõ ràng, mỗi nơi một kiểu","2":"Có logo nhưng không có brand guide hoặc không nhất quán","3":"Có brand identity cơ bản nhưng chưa được áp dụng nhất quán","4":"Có brand guide và được áp dụng nhất quán ở hầu hết các điểm chạm","5":"Brand identity toàn diện: logo + màu + typography + giọng điệu + template, nhất quán mọi nơi"}' WHERE question_id = 'pb_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không biết, không có phản hồi cụ thể về brand","2":"Chỉ biết giá rẻ hoặc gần nhà","3":"Biết một vài đặc điểm nhưng không có narrative rõ ràng","4":"Có một số từ khóa mà bệnh nhân thường nhắc đến","5":"Brand perception mạnh mẽ: bệnh nhân có thể mô tả phòng khám bằng 3-5 từ cụ thể và tích cực"}' WHERE question_id = 'pb_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có USP, cạnh tranh hoàn toàn bằng giá","2":"Có một vài lợi thế nhưng đối thủ có thể dễ dàng sao chép","3":"Có USP tiềm năng nhưng chưa được khai thác và truyền thông","4":"Có USP rõ ràng và được truyền thông đến bệnh nhân","5":"USP mạnh mẽ và bền vững: dịch vụ đặc biệt, công nghệ độc quyền, hoặc thương hiệu cá nhân mạnh"}' WHERE question_id = 'pb_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có câu chuyện, chỉ là một phòng khám như bao phòng khám khác","2":"Có câu chuyện trong đầu nhưng chưa viết ra hoặc chia sẻ","3":"Có câu chuyện được chia sẻ nhưng chưa thực sự cảm hứng","4":"Câu chuyện được viết rõ, chia sẻ với bệnh nhân và đội ngũ","5":"Câu chuyện mạnh mẽ, truyền cảm hứng, là nền tảng thương hiệu"}' WHERE question_id = 'pb_q5';

-- === 28: tu-van-ban-hang-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Thường đề xuất ngay mà không hỏi","2":"Có hỏi nhưng không lắng nghe đủ","3":"Lắng nghe tốt nhưng chưa đề xuất phù hợp","4":"Lắng nghe để hiểu + đề xuất giải pháp phù hợp","5":"Tư vấn xuất sắc: lắng nghe sâu + đề xuất tối ưu + build trust"}' WHERE question_id = 'tv_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Nói giá rồi để đó","2":"Có trình bày nhưng bệnh nhân vẫn không hiểu giá trị","3":"Trình bày rõ ràng nhưng gây áp lực","4":"Trình bày rõ ràng, không áp lực, bệnh nhân hiểu được giá trị","5":"Trình bày giá trị xuất sắc: transparent, value-based, builds trust"}' WHERE question_id = 'tv_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không xử lý được, bệnh nhân đi luôn","2":"Xử lý yếu, mất 50% deals","3":"Xử lý được nhưng chưa tự tin","4":"Xử lý tốt, giữ được phần lớn deals","5":"Xử lý xuất sắc: mọi objection đều có playbook, win rate cao"}' WHERE question_id = 'tv_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không follow-up, bệnh nhân đi rồi thì thôi","2":"Follow-up một lần nhưng không có hệ thống","3":"Follow-up thường xuyên nhưng không có template","4":"Có hệ thống follow-up: template + timing + tracking","5":"Full follow-up engine: automated + personalized + tracked + optimized"}' WHERE question_id = 'tv_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không được đào tạo","2":"Đào tạo sơ sài, không có hệ thống","3":"Có đào tạo cơ bản nhưng chưa thường xuyên","4":"Đào tạo định kỳ và có đánh giá","5":"Full sales training program: scripts + objection handling + role-play + KPIs"}' WHERE question_id = 'tv_q5';

-- === 29: marketing-online-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có website","2":"Có website nhưng cũ, không tối ưu di động","3":"Có website cơ bản, thông tin đầy đủ","4":"Website chuyên nghiệp, tối ưu di động, có booking online","5":"Website xuất sắc: SEO + booking + patient education + conversion optimization"}' WHERE question_id = 'mo_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có Google Business Profile","2":"Có nhưng thông tin không đầy đủ hoặc không cập nhật","3":"Có, thông tin đầy đủ, nhưng không quản lý reviews","4":"Có, quản lý tốt, có reviews và phản hồi đều đặn","5":"Google Business Profile xuất sắc: reviews 5*, photos, posts, Q&A, insights"}' WHERE question_id = 'mo_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có mạng xã hội","2":"Có nhưng không active","3":"Active nhưng content không đều","4":"Content đều đặn, có engagement","5":"Social media strategy: multi-platform + content calendar + engagement + paid ads"}' WHERE question_id = 'mo_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có reviews hoặc toàn negative","2":"Có vài reviews nhưng không quản lý","3":"Có reviews tốt nhưng chưa chủ động thu thập","4":"Reviews tốt, chủ động thu thập, có phản hồi","5":"Reputation management: 5* average + proactive review collection + response + NPS tracking"}' WHERE question_id = 'mo_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có chiến lược, làm ad-hoc","2":"Có một số hoạt động nhưng không có chiến lược","3":"Có chiến lược chung nhưng không chi tiết","4":"Có chiến lược + content plan + channel prioritization","5":"Full digital strategy: ICP + journey + attribution + automation + ROI tracking"}' WHERE question_id = 'mo_q5';

-- === 30: thu-vi-tri-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không biết đối thủ","2":"Biết một vài đối thủ nhưng không rõ chi tiết","3":"Biết đối thủ chính nhưng không phân tích sâu","4":"Biết rõ 3-5 đối thủ, có phân tích SWOT cơ bản","5":"Phân tích SWOT đầy đủ + competitive positioning + opportunity mapping"}' WHERE question_id = 'tvtri_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không biết điểm mạnh độc nhất","2":"Có một vài ý tưởng nhưng chưa rõ ràng","3":"Biết điểm mạnh nhưng chưa khai thác","4":"Có 1-2 lợi thế rõ ràng và đang khai thác","5":"Lợi thế cạnh tranh độc đáo, khó sao chép, được truyền thông hiệu quả"}' WHERE question_id = 'tvtri_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có chiến lược","2":"Có suy nghĩ nhưng không có kế hoạch","3":"Có kế hoạch ngắn hạn","4":"Có cả ngắn hạn và dài hạn, có KPIs","5":"Strategic planning: vision + 1-3-5 year plans + scenario planning + quarterly reviews"}' WHERE question_id = 'tvtri_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có khác biệt rõ ràng","2":"Có một vài khác biệt nhưng bệnh nhân không biết","3":"Có khác biệt rõ ràng nhưng chưa được truyền thông tốt","4":"Khác biệt rõ ràng và được truyền thông đến bệnh nhân","5":"Brand differentiation mạnh mẽ: được nhận diện vì lý do đúng và không thể sao chép"}' WHERE question_id = 'tvtri_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có tầm nhìn","2":"Có suy nghĩ nhưng không rõ ràng","3":"Có tầm nhìn chung nhưng không cụ thể","4":"Có tầm nhìn 3-5 năm rõ ràng","5":"Tầm nhìn truyền cảm hứng: đội ngũ gắn kết vì tầm nhìn chung"}' WHERE question_id = 'tvtri_q5';

-- === 31: thich-ung-dung-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không dùng phần mềm, quản lý bằng sổ sách hoặc Excel","2":"Dùng Excel hoặc phần mềm không chuyên cho nha khoa","3":"Có phần mềm nha khoa cơ bản (quản lý bệnh nhân hoặc đặt lịch)","4":"Phần mềm nha khoa đầy đủ: bệnh nhân + lịch + tài chính + inventory","5":"Hệ thống tích hợp toàn diện — phần mềm + app + tự động hóa"}' WHERE question_id = 'tu_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không theo dõi xu hướng","2":"Biết có xu hướng nhưng không phản ứng","3":"Phản ứng chậm khi đã thay đổi lớn","4":"Theo dõi và phản ứng kịp thời","5":"Chủ động dự đoán và thử nghiệm xu hướng mới"}' WHERE question_id = 'tu_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không sẵn sàng thay đổi","2":"Sẵn sàng nhưng không biết làm gì","3":"Sẵn sàng và đã thay đổi một vài lần","4":"Chủ động thay đổi khi thấy cơ hội","5":"Transformation-ready: agile, experimental, fast learner"}' WHERE question_id = 'tu_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không thể thích ứng với quy trình mới","2":"Chậm thích ứng, cần nhiều thời gian","3":"Thích ứng được sau khi đào tạo","4":"Thích ứng nhanh, đào tạo ngắn","5":"Continuous learners: luôn sẵn sàng học và thử cái mới"}' WHERE question_id = 'tu_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không học thêm gì","2":"Thỉnh thoảng đọc nhưng không liên quan","3":"Học hỏi từ các nguồn không có hệ thống","4":"Có hệ thống học hỏi: courses, communities, mentors","5":"Learning organization: luôn học, luôn cải tiến, luôn ở forefront"}' WHERE question_id = 'tu_q5';

-- === 32: thuong-hieu-ca-nhan-check ===
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có online presence","2":"Có profile nhưng không chuyên nghiệp","3":"Có online presence nhưng không nhất quán","4":"Online presence tốt: professional, consistent, clear messaging","5":"Personal brand mạnh: recognized authority, engaged community, consistent content"}' WHERE question_id = 'thcn_q1';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không chia sẻ nội dung","2":"Chia sẻ nhưng không đều đặn","3":"Chia sẻ đều đặn nhưng chưa có chiến lược","4":"Content strategy tốt: ngành + giáo dục + personal brand","5":"Content authority: recognized expert, media appearances, speaking engagements"}' WHERE question_id = 'thcn_q2';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không được công nhận là chuyên gia","2":"Được biết nhưng chưa có positioning rõ ràng","3":"Được công nhận trong cộng đồng nhỏ","4":"Được công nhận rộng rãi: reviews, referrals, media","5":"Industry authority: awards, media, speaking, advisory roles"}' WHERE question_id = 'thcn_q3';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không có mạng lưới","2":"Có vài kết nối nhưng không chủ động","3":"Có mạng lưới cơ bản","4":"Mạng lưới mạnh: cộng đồng + referral partners + advisory board","5":"Strategic network: key relationships + influence + mutual growth"}' WHERE question_id = 'thcn_q4';
UPDATE survey_question SET scale_labels_vi = '{"1":"Không nhất quán, mỗi nơi một phong cách","2":"Tương đối nhất quán","3":"Nhất quán trên 1-2 nền tảng","4":"Nhất quán trên hầu hết nền tảng","5":"Fully consistent: everywhere + always + intentional"}' WHERE question_id = 'thcn_q5';
